[workspace]
authors = ["Girish Vλas <vgd.vyas17@gmail.com>"]
channels = ["conda-forge"]
name = "dnds"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
fmt = "gofmt -w *.go"
vet = "go vet *.go"
test = "go test *.go"

[dependencies]
r = ">=4.5,<4.6"
gcc_linux-64 = ">=15.2.0,<16"
go = ">=1.26.4,<2"
pre-commit = ">=4.6.0,<5"
