[workspace]
authors = ["Girish Vλas <vgd.vyas17@gmail.com>"]
channels = ["conda-forge"]
name = "dnds"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
fmt = "gofmt -w src/*.go"
vet = "go vet ./src/..."
test = "go test ./src/..."

[dependencies]
r = ">=4.5,<4.6"
gcc_linux-64 = ">=15.2.0,<16"
go = ">=1.26.4,<2"
pre-commit = ">=4.6.0,<5"
jupyter = ">=1.1.1,<2"
ipykernel = ">=7.3.0,<8"
numpy = ">=2.5.2,<3"
pandas = ">=3.0.5,<4"
scipy = ">=1.18.0,<2"
statsmodels = ">=0.14.6,<0.15"
